name: 'Crowdin languages progress'
description: 'Add languages progress to your README.md'
author: 'Benjamin Jonard'

branding:
  icon: 'type'
  color: 'red'

inputs:
  languages_per_row:
    description: 'Number of languages displayed on each row'
    default: '2'
    required: false
  minimum_completion_percent:
    description: 'The minimum progress value in % the language must be to be considered available'
    default: '80'
    required: false
  file:
    description: 'The markdown file'
    default: 'README.md'
    required: false

runs:
  using: 'node16'
  main: 'dist/index.js'
